# Generated by Django 3.0.4 on 2020-04-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.Region')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.Country')),
                ('region_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('is_company', models.BooleanField(default=True)),
                ('nrc', models.CharField(blank=True, max_length=10, null=True)),
                ('nif', models.CharField(blank=True, max_length=15, null=True)),
                ('nis', models.CharField(blank=True, max_length=15, null=True)),
                ('nai', models.CharField(blank=True, max_length=11, null=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NA', 'Not specified')], default='M', max_length=2)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.State')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.Category')),
            ],
        ),
    ]
