# Generated by Django 3.0.4 on 2020-04-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200401_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='depth',
        ),
    ]
